name: CI/CD

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Specify your Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  deploy-to-play-store:
    name: Deploy to Play Store
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Specify your Flutter version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > android/know_keeper-release-key.jks

      - name: Decode Service Account Key
        env:
          ENCODED_SERVICE_ACCOUNT_KEY: ${{ secrets.ENCODED_SERVICE_ACCOUNT_KEY }}
        run: |
          echo $ENCODED_SERVICE_ACCOUNT_KEY | base64 -d > knowkeeper-fastlane-d674e90b76be.json

      - name: Build and Deploy to Play Store
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd android
          bundle exec fastlane beta
